apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: observability
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.132.0
  mode: deployment
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}

    processors:
      batch: {}
      metricsgeneration:
        dimensions:
          - name: http.method
          - name: http.status_code
          - name: service.name

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
      otlp/jaeger:
        endpoint: simplest-collector.observability.svc.cluster.local:4317
        tls:
          insecure: true
      debug: {}

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, metricsgeneration]
          exporters: [otlp/jaeger, debug]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
