apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: default
source:
  repoURL: https://grafana.github.io/helm-charts
  chart: grafana
  targetRevision: 8.3.5
  helm:
    releaseName: grafana
    valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
