---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hotrod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/olenahaldevops/observability.git
    targetRevision: main
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true