apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/olenahaldevops/observability.git
    targetRevision: main
    path: otel-collector
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
