server:
  service:
    type: ClusterIP
  persistentVolume:
    enabled: false

  extraScrapeConfigs: |
    - job_name: 'otel-collector'
      scrape_interval: 10s
      static_configs:
        - targets: ['otel-collector-collector.observability.svc.cluster.local:8889']

alertmanager:
  enabled: false

pushgateway:
  enabled: false