server:
  service:
    type: ClusterIP
  persistentVolume:
    enabled: false

alertmanager:
  enabled: false
pushgateway:
  enabled: false

serviceAccounts:
  server:
    create: true

serviceMonitor:
  enabled: true

prometheusSpec:
  serviceMonitorSelector:
    matchExpressions:
      - key: release
        operator: In
        values:
          - prometheus
  podMonitorSelector: {}