name: Observability validation

on:
  push:
    branches: ["**"]
    paths:
      - 'apps/*.yaml'
      - 'argocd-apps/*.yaml'
      - 'grafana/*.yaml'
      - 'jaeger/*.yaml'
      - 'otel-collector/*.yaml'
      - 'prometheus/*.yaml'
  pull_request:
    paths:
      - 'apps/*.yaml'
      - 'argocd-apps/*.yaml'
      - 'grafana/*.yaml'
      - 'jaeger/*.yaml'
      - 'otel-collector/*.yaml'
      - 'prometheus/*.yaml'

concurrency:
  group: obs-validate-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: sudo apt-get update && sudo apt-get install -y yamllint
      - name: Lint YAML
        run: |
          yamllint -s \
            apps/*.yaml argocd-apps/*.yaml grafana/*.yaml jaeger/*.yaml \
            otel-collector/*.yaml prometheus/*.yaml

  validate-otel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yq
        run: |
          curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 \
            -o /usr/local/bin/yq && chmod +x /usr/local/bin/yq

      - name: Extract Collector config to temp file
        id: extract
        shell: bash
        run: |
          set -euo pipefail
          SRC="otel-collector/otel-collector.yaml"
          OUT="/tmp/collector-config.yaml"

          if [ ! -f "$SRC" ]; then
            echo "no_config=true" >> "$GITHUB_OUTPUT"
            echo "No OTel collector manifest found, skipping."
            exit 0
          fi

          # Is this a K8s manifest?
          if yq -e '.apiVersion and .kind' "$SRC" >/dev/null 2>&1; then
            KIND=$(yq -r '.kind' "$SRC")
            case "$KIND" in
              OpenTelemetryCollector)
                # spec.config may be a YAML block string — yq will write it out as YAML
                yq '.spec.config' "$SRC" > "$OUT"
                ;;
              ConfigMap)
                # Try common keys inside data
                yq -r '.data["collector.yaml"] // .data["otel-collector.yaml"] // .data["config.yaml"] // empty' "$SRC" > "$OUT" || true
                ;;
              *)
                echo "Unsupported K8s kind for extraction: $KIND"
                exit 1
                ;;
            esac
          else
            # Plain collector config (no apiVersion/kind)
            cp "$SRC" "$OUT"
          fi

          # Basic sanity: must have 'service:' section
          if ! yq -e '.service' "$OUT" >/dev/null 2>&1; then
            echo "Extracted file lacks a 'service' section. Not a valid collector config."
            echo "no_config=true" >> "$GITHUB_OUTPUT"
            exit 1
          fi

          echo "config_path=$OUT" >> "$GITHUB_OUTPUT"

      - name: Validate OTel collector config (validate subcommand)
        if: steps.extract.outputs.no_config != 'true'
        env:
          OTELCOL_VERSION: "0.132.0"   # or bump to 0.133.0
        shell: bash
        run: |
          set -euo pipefail
          IMG="otel/opentelemetry-collector-contrib:${OTELCOL_VERSION}"
          if ! docker pull "$IMG" >/dev/null 2>&1; then
            echo "Docker Hub tag not found, using GHCR…"
            IMG="ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:${OTELCOL_VERSION}"
            docker pull "$IMG"
          fi

          docker run --rm -v "${{ steps.extract.outputs.config_path }}:/cfg.yaml" "$IMG" \
            validate --config=/cfg.yaml

  kubeconform-manifests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install kubeconform
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz \
          | tar -xz kubeconform && sudo mv kubeconform /usr/local/bin/
      - name: Validate K8s manifests (apps + argocd-apps + jaeger)
        run: |
          set -e
          FILES=$(ls apps/*.yaml argocd-apps/*.yaml jaeger/*.yaml 2>/dev/null || true)
          if [ -z "$FILES" ]; then
            echo "No Kubernetes manifests to validate."
            exit 0
          fi
          kubeconform \
            -strict -summary \
            --schema-location default \
            --schema-location "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/{{.NormalizedKubernetesVersion}}-standalone/{{.ResourceKind}}.json" \
            --schema-location "https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json" \
            $FILES
            
  helm-prometheus:
    name: Helm chart validation (prometheus/)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Helm + kubeconform
        run: |
          curl -L https://get.helm.sh/helm-v3.15.3-linux-amd64.tar.gz \
          | tar -xz && sudo mv linux-amd64/helm /usr/local/bin/helm
          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz \
          | tar -xz kubeconform && sudo mv kubeconform /usr/local/bin/

      - name: Helm repos
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add jaegertracing https://jaegertracing.github.io/helm-charts
          helm repo update

      - name: Build chart dependencies
        run: |
          if [ -f prometheus/Chart.yaml ]; then
            rm -f prometheus/Chart.lock
            rm -rf prometheus/charts
            helm dependency build prometheus
            echo "== Dependency list =="
            helm dependency list prometheus || true
          else
            echo "No Helm chart in prometheus/ — skipping deps."
          fi

      - name: Helm lint (with subcharts)
        run: |
          if [ -f prometheus/Chart.yaml ]; then
            helm lint prometheus --with-subcharts
          else
            echo "No Helm chart in prometheus/ — skipping lint."
          fi

      - name: Render chart and kube-validate
        run: |
          if [ -f prometheus/Chart.yaml ]; then
            # include values.yaml if it exists
            VALS_ARG=""
            if [ -f prometheus/values.yaml ]; then
              VALS_ARG="-f prometheus/values.yaml"
            fi
            helm template prom prometheus $VALS_ARG > /tmp/prom-rendered.yaml
            # Validate rendered manifests (standard resources)
            kubeconform -strict -summary \
              --schema-location default \
              --schema-location "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/{{.NormalizedKubernetesVersion}}-standalone/{{.ResourceKind}}.json" \
              /tmp/prom-rendered.yaml
          else
            echo "No Helm chart in prometheus/ — skipping render/validate."
          fi
